ENH: Update CI for ITK 5.2rc03
InsightSoftwareConsortium/ITKMeshToPolyData pull request #35
Opened 2021-03-15 18:42 UTC by tbirdso

2021-03-15 18:58 UTC, dzenanz commented on .github/workflows/build-test-package.yml
> +          - itk-python-git-tag: "v5.2rc03"
Probably also update `setup.py` to ref 5.2rc3 and increase version number.

2021-03-15 19:22 UTC, tbirdso commented
Updated ITK commit tags to `7548a390d71dc25b80e792703ee3cfea17853a99` due to blocking build issue in `5.2rc03` tagged commit.

2021-03-15 19:23 UTC, dzenanz approved these changes

2021-03-16 01:59 UTC, thewtex requested changes
`PyVectorContainer` has been integrated into upstream ITK, so:

https://github.com/InsightSoftwareConsortium/ITKMeshToPolyData/blob/master/wrapping/PyVectorContainerBuffer.i.in
https://github.com/InsightSoftwareConsortium/ITKMeshToPolyData/blob/master/wrapping/itkPyVectorContainer.wrap
https://github.com/InsightSoftwareConsortium/ITKMeshToPolyData/blob/c79e2182934724ccb79a53ca8b5acd863fb99d93/wrapping/PyBuffer.i.init
https://github.com/InsightSoftwareConsortium/ITKMeshToPolyData/blob/c79e2182934724ccb79a53ca8b5acd863fb99d93/wrapping/CMakeLists.txt#L3

should also be removed.

2021-03-16 01:59 UTC, thewtex commented on .github/workflows/build-test-package.yml
> -          - itk-python-git-tag: "v5.1.2"
Tagged releases, i.e. `v5.2rc03` are only available for the Python package builds, but this is only what is required.

2021-03-16 01:59 UTC, thewtex commented on .github/workflows/build-test-package.yml
> +          - itk-python-git-tag: "7548a390d71dc25b80e792703ee3cfea17853a99"
Tagged releases, i.e. `v5.2rc03` are only available for the Python package builds, but this is only what is required.

2021-03-16 01:59 UTC, thewtex commented on .github/workflows/build-test-package.yml
> +          - itk-python-git-tag: "7548a390d71dc25b80e792703ee3cfea17853a99"
Tagged releases, i.e. `v5.2rc03` are only available for the Python package builds, but this is only what is required.

2021-03-17 14:34 UTC, thewtex approved these changes

2021-03-17 14:35 UTC, thewtex commented
@tbirdso thanks!

2021-03-17 14:35 UTC, merged